#!/bin/bash

dir="."
if [ -n "$1" ]; then
	dir="$1"
fi

total=$(find -name "*.key" | wc -l)
zeroes=$(python -c "import math; print int(math.ceil(math.log($total + 1, 10)))")
count=0

if [ "$total" != "0" ]; then
	find "$dir" -name "*.key" | while read keyfile; do
		encfile="$(echo $keyfile | rev | colrm 1 4 | rev).enc"
		((count=count+1))
		printf "%${zeroes}d / $total\n" $count
		if [ -e "$encfile" ]; then
			rsa-decrypt --rm -i "$encfile" -k "$keyfile"
		else
			echo "ERROR: unable to find $encfile"
		fi
	done
else
	echo "No files found!"
fi
