#!/bin/bash

remove="false"
keyfile="$HOME/.ssh/id_rsa.pub.pem"
while [[ $# > 0 ]]; do
	key="$1"
	case $key in
		-k|--key)
		keyfile="$2"
		shift # past argument
		;;
		--rm)
		remove="true"
		;;
		*)
		# unknown option
		;;
	esac
	shift # past argument or value
done

total=$(find -type f | wc -l)
zeroes=$(python -c "import math; print max(3, int(math.ceil(math.log($total + 1, 10))))")
count=0

find -type f | sort | while read file; do
	printf "%${zeroes}d / $total\n" $count
	rsa-encrypt -k "$keyfile" -i "$file" -o $(printf "%0${zeroes}d" $count)
	if [ "$?" != "0" ]; then
		remove="false"
	fi
	if [ "$remove" == "true" ]; then
		rm "$file"
	fi
	((count=count+1))
done
if [ "$remove" == "true" ]; then
	find -type d | sort | tail -n +2 | tac | while read dir; do
		rmdir "$dir"
	done
fi
