#!/bin/bash

remove="false"
keyfile="$HOME/.ssh/id_rsa.pub.pem"
while [[ $# > 0 ]]; do
	key="$1"
	case $key in
		-k|--key)
		keyfile="$2"
		shift # past argument
		;;
		--rm)
		remove="true"
		;;
		*)
		# unknown option
		;;
	esac
	shift # past argument or value
done

total=$(find -type f | wc -l)
if [ $total -gt 1000 ]; then
	echo "too many files!"
	exit 1
fi

count=0
find -type f | sort | while read file; do
	rsa-encrypt -k "$keyfile" -i "$file" -o $(printf "%03d" $count)
	if [ "$remove" == "true" ] && [ "$?" == "0" ]; then
		rm "$file"
	fi
	((count=count+1))
done
