#!/bin/bash

keyfile="$1"
inputfile="$2"
outputfile="$3"
if [ ! -e "$keyfile" ]; then
	echo "ERROR: $keyfile not found"
	exit 1
elif [ ! -e "$inputfile" ]; then
	echo "ERROR: $inputfile not found"
	exit 1
fi

if [ -z "$outputfile" ]; then
	outputfile="$inputfile.dec"
fi
if [ -e "$outputfile" ]; then
	echo "ERROR: $outputfile already exists"
	exit 1
fi

tempkey="/run/shm/tempkey-$RANDOM.bin"

# decrypts key for AES-256
openssl rsautl -decrypt -inkey $HOME/.ssh/id_rsa < "$keyfile" > $tempkey

# decrypts inputfile
if [ -n "$(which pv)" ]; then
	openssl enc -d -aes-256-cbc -in "$inputfile" -pass file:$tempkey | pv > "$outputfile"
else
	openssl enc -d -aes-256-cbc -in "$inputfile" -pass file:$tempkey > "$outputfile"
fi
rm $tempkey
